# Generated by Django 5.1.3 on 2024-11-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_guest',
            field=models.IntegerField(null=True),
        ),
    ]
