# Generated by Django 5.1.3 on 2024-11-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_booking_booking_date_booking_number_of_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(null=True),
        ),
    ]
